name: test

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install modules ("npm i")
      run: npm i
    - name: Run tests ("npm run test")
      run: npm run test
